import React, { useMemo, useState } from 'react';
import { Edit2, Plus, Trash2 } from 'lucide-react'; import RecordModal from './RecordModal'; import StatusBadge from './StatusBadge';
const statuses=[{value:'untested',label:'Sin probar'},{value:'validation',label:'Necesita validación'},{value:'approved',label:'Aprobado'},{value:'failed',label:'Fallido'}];
export default function CasesView({ cases, tests, selected, setSelected, actions }) {
 const [editing,setEditing]=useState(); const [filters,setFilters]=useState({family:'',stitch:'',fabric:'',status:'',confidence:''});
 const fields=useMemo(()=>[{name:'test_id',label:'Prueba',kind:'select',required:true,options:[{value:'',label:'Seleccionar'},...tests.map(t=>({value:t.id,label:t.name}))]},{name:'case_id',label:'Case ID',required:true},{name:'geometric_family',label:'Familia geométrica'},{name:'name',label:'Nombre',required:true},...['nominal_width:Anchura nominal','observed_width:Anchura observada','height:Altura','area:Área','hole_count:Número de huecos','island_count:Número de islas','minimum_bridge_thickness:Grosor mínimo de puente'].map(x=>{const [name,label]=x.split(':');return{name,label,kind:'number'}}),{name:'top_stitch_type',label:'Puntada superior'},{name:'spacing_mode',label:'Modo de espaciado'},{name:'spacing_value',label:'Valor de espaciado',kind:'number'},{name:'automatic_split',label:'División automática',kind:'checkbox'},{name:'underlay_1',label:'Underlay 1'},{name:'underlay_2',label:'Underlay 2'},{name:'compensation',label:'Compensación',kind:'number'},{name:'angle',label:'Ángulo',kind:'number'},...['trim_count:Recortes','jump_count:Jumps','stitch_count:Puntadas'].map(x=>{const [name,label]=x.split(':');return{name,label,kind:'number'}}),{name:'visual_result',label:'Resultado visual',kind:'textarea'},{name:'physical_result',label:'Resultado físico',kind:'textarea'},{name:'confidence',label:'Confianza (%)',kind:'number'},{name:'status',label:'Estado',kind:'select',options:statuses},{name:'notes',label:'Notas',kind:'textarea',wide:true}], [tests]);
 const filtered=cases.filter(c=>(!filters.family||c.geometric_family===filters.family)&&(!filters.stitch||c.top_stitch_type===filters.stitch)&&(!filters.fabric||tests.find(t=>t.id===c.test_id)?.fabric_profile===filters.fabric)&&(!filters.status||c.status===filters.status)&&(!filters.confidence||Number(c.confidence||0)>=Number(filters.confidence)));
 const choices=(key)=>[...new Set(cases.map(c=>key==='fabric'?tests.find(t=>t.id===c.test_id)?.fabric_profile:c[key]).filter(Boolean))];
 return <section><div className="mb-3 flex items-center"><div><h2 className="font-heading text-sm font-bold">Casos</h2><p className="text-xs text-muted-foreground">Selecciona dos o más para compararlos.</p></div><button onClick={()=>setEditing('new')} className="ml-auto flex items-center gap-1 rounded-md bg-primary px-3 py-2 text-xs font-bold text-primary-foreground"><Plus className="h-3.5 w-3.5"/>Nuevo caso</button></div>
 <div className="mb-3 grid grid-cols-2 gap-2 md:grid-cols-5">{[['family','Familia','geometric_family'],['stitch','Puntada','top_stitch_type'],['fabric','Tela','fabric'],['status','Estado','status']].map(([key,label,source])=><select key={key} value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})} className="rounded-md border border-input bg-background px-2 py-2 text-xs"><option value="">{label}: todas</option>{choices(source).map(v=><option key={v}>{v}</option>)}</select>)}<input type="number" placeholder="Confianza mínima" value={filters.confidence} onChange={e=>setFilters({...filters,confidence:e.target.value})} className="rounded-md border border-input bg-background px-2 py-2 text-xs"/></div>
 <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map(c=><article key={c.id} className={`rounded-lg border p-3 ${selected.includes(c.id)?'border-primary bg-primary/5':'border-border bg-card'}`}><div className="flex items-start gap-2"><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>setSelected(selected.includes(c.id)?selected.filter(id=>id!==c.id):[...selected,c.id])}/><div className="min-w-0 flex-1"><h3 className="truncate text-xs font-bold">{c.case_id} · {c.name}</h3><p className="text-[10px] text-muted-foreground">{c.geometric_family||'Sin familia'} · {c.top_stitch_type||'Sin puntada'}</p></div><StatusBadge status={c.status}/></div><div className="mt-3 grid grid-cols-3 gap-2 text-[10px]"><span>Ancho<br/><b>{c.observed_width??'—'} mm</b></span><span>Huecos<br/><b>{c.hole_count??0}</b></span><span>Islas<br/><b>{c.island_count??0}</b></span><span>Underlay<br/><b>{c.underlay_1||'—'}</b></span><span>Espaciado<br/><b>{c.spacing_value??'—'}</b></span><span>Confianza<br/><b>{c.confidence??'—'}%</b></span></div><div className="mt-3 flex justify-end gap-2"><button onClick={()=>setEditing(c)} className="text-accent"><Edit2 className="h-3.5 w-3.5"/></button><button onClick={()=>confirm('¿Eliminar este caso?')&&actions.remove('cases',c.id)} className="text-destructive"><Trash2 className="h-3.5 w-3.5"/></button></div></article>)}</div>
 {editing&&<RecordModal title={editing==='new'?'Nuevo caso':'Editar caso'} fields={fields} initial={editing==='new'?{status:'untested',hole_count:0,island_count:0}:editing} onClose={()=>setEditing(null)} onSave={v=>editing==='new'?actions.create('cases',v):actions.update('cases',editing.id,v)} upload={actions.upload}/>}</section>;
}