import React, { useEffect, useState } from 'react';
import { X } from 'lucide-react';
const parseValue = (field, value) => field.kind === 'number' ? (value === '' ? undefined : Number(value)) : field.kind === 'checkbox' ? value : field.kind === 'json' ? (value.trim() ? JSON.parse(value) : field.array ? [] : {}) : value;
export default function RecordModal({ title, fields, initial, onClose, onSave, upload }) {
  const [form, setForm] = useState({}); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => setForm(Object.fromEntries(fields.map((f) => [f.name, f.kind === 'json' ? JSON.stringify(initial?.[f.name] ?? (f.array ? [] : {}), null, 2) : initial?.[f.name] ?? (f.kind === 'checkbox' ? false : '')]))), [initial, fields]);
  const submit = async (e) => { e.preventDefault(); setSaving(true); setError(''); try { const value = Object.fromEntries(fields.map((f) => [f.name, parseValue(f, form[f.name])])); await onSave(value); onClose(); } catch (err) { setError(err?.message || 'No se pudo guardar. Revisa los campos.'); } finally { setSaving(false); } };
  const chooseFile = async (field, file) => { if (!file) return; setSaving(true); try { const url = await upload(file); setForm((v) => ({ ...v, [field]: url })); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-3"><form onSubmit={submit} className="max-h-[92vh] w-full max-w-3xl overflow-auto rounded-xl border border-border bg-card p-4 shadow-2xl">
    <div className="mb-4 flex items-center"><h2 className="font-heading text-sm font-bold">{title}</h2><button type="button" onClick={onClose} className="ml-auto p-1 text-muted-foreground"><X className="h-4 w-4" /></button></div>
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{fields.map((f) => <label key={f.name} className={f.wide ? 'sm:col-span-2' : ''}><span className="mb-1 block text-[10px] font-semibold uppercase text-muted-foreground">{f.label}</span>{f.kind === 'select' ? <select required={f.required} value={form[f.name] ?? ''} onChange={(e) => setForm({ ...form, [f.name]: e.target.value })} className="w-full rounded-md border border-input bg-background px-3 py-2 text-xs">{f.options.map((o) => <option key={o.value ?? o} value={o.value ?? o}>{o.label ?? o}</option>)}</select> : f.kind === 'textarea' || f.kind === 'json' ? <textarea required={f.required} rows={f.kind === 'json' ? 5 : 3} value={form[f.name] ?? ''} onChange={(e) => setForm({ ...form, [f.name]: e.target.value })} className="w-full rounded-md border border-input bg-background px-3 py-2 font-mono text-xs" /> : f.kind === 'checkbox' ? <input type="checkbox" checked={!!form[f.name]} onChange={(e) => setForm({ ...form, [f.name]: e.target.checked })} className="h-4 w-4" /> : f.kind === 'file' ? <div><input type="file" accept={f.accept} onChange={(e) => chooseFile(f.name, e.target.files?.[0])} className="w-full text-xs" /><span className="text-[10px] text-muted-foreground">{form[f.name] ? 'Archivo cargado' : 'Sin archivo'}</span></div> : <input required={f.required} type={f.kind === 'number' ? 'number' : f.kind || 'text'} step={f.step || 'any'} value={form[f.name] ?? ''} onChange={(e) => setForm({ ...form, [f.name]: e.target.value })} className="w-full rounded-md border border-input bg-background px-3 py-2 text-xs" />}</label>)}</div>
    {error && <p className="mt-3 text-xs text-destructive">{error}</p>}<div className="mt-4 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-md border border-border px-3 py-2 text-xs">Cancelar</button><button disabled={saving} className="rounded-md bg-primary px-3 py-2 text-xs font-bold text-primary-foreground">{saving ? 'Guardando…' : 'Guardar'}</button></div>
  </form></div>;
}