import React, { useMemo, useState } from 'react';
import { Edit2, Plus, Trash2 } from 'lucide-react';
import RecordModal from './RecordModal'; import StatusBadge from './StatusBadge';
const statusOptions = [{ value: 'untested', label: 'Sin probar' },{ value: 'validation', label: 'Necesita validación' },{ value: 'approved', label: 'Aprobado' },{ value: 'failed', label: 'Fallido' }];
export default function TestsView({ tests, actions }) {
  const [editing, setEditing] = useState(); const fields = useMemo(() => [
    { name:'name',label:'Nombre',required:true },{ name:'version',label:'Versión' },{ name:'emb_file_url',label:'Archivo EMB',kind:'file',accept:'.emb' },{ name:'source_image_url',label:'Imagen fuente',kind:'file',accept:'image/*' },
    { name:'fabric_profile',label:'Perfil de tela' },{ name:'width_mm',label:'Ancho (mm)',kind:'number' },{ name:'height_mm',label:'Alto (mm)',kind:'number' },{ name:'test_date',label:'Fecha',kind:'date' },{ name:'status',label:'Estado',kind:'select',options:statusOptions },{ name:'notes',label:'Notas',kind:'textarea',wide:true },
  ], []);
  const openValue = editing && editing !== 'new' ? { ...editing, width_mm: editing.dimensions?.width_mm, height_mm: editing.dimensions?.height_mm } : { status:'untested' };
  const save = (value) => { const { width_mm, height_mm, ...rest } = value; const payload = { ...rest, dimensions:{ width_mm, height_mm } }; return editing === 'new' ? actions.create('tests', payload) : actions.update('tests', editing.id, payload); };
  return <section><div className="mb-3 flex items-center"><div><h2 className="font-heading text-sm font-bold">Pruebas</h2><p className="text-xs text-muted-foreground">Láminas de investigación Hatch.</p></div><button onClick={() => setEditing('new')} className="ml-auto flex items-center gap-1 rounded-md bg-primary px-3 py-2 text-xs font-bold text-primary-foreground"><Plus className="h-3.5 w-3.5"/>Nueva prueba</button></div>
    <div className="overflow-x-auto rounded-lg border border-border"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-muted/50 text-muted-foreground"><tr>{['Nombre','Versión','Tela','Dimensiones','Fecha','Estado','Acciones'].map((h)=><th key={h} className="px-3 py-2">{h}</th>)}</tr></thead><tbody>{tests.map((t)=><tr key={t.id} className="border-t border-border"><td className="px-3 py-2 font-semibold">{t.name}{t.is_demo && <small className="ml-2 text-amber-300">DEMO</small>}</td><td className="px-3 py-2">{t.version||'—'}</td><td className="px-3 py-2">{t.fabric_profile||'—'}</td><td className="px-3 py-2">{t.dimensions?.width_mm||'—'} × {t.dimensions?.height_mm||'—'} mm</td><td className="px-3 py-2">{t.test_date||'—'}</td><td className="px-3 py-2"><StatusBadge status={t.status}/></td><td className="px-3 py-2"><button onClick={()=>setEditing(t)} className="mr-2 text-accent"><Edit2 className="h-3.5 w-3.5"/></button><button onClick={()=>confirm('¿Eliminar esta prueba?')&&actions.remove('tests',t.id)} className="text-destructive"><Trash2 className="h-3.5 w-3.5"/></button></td></tr>)}</tbody></table></div>
    {editing && <RecordModal title={editing==='new'?'Nueva prueba':'Editar prueba'} fields={fields} initial={openValue} onClose={()=>setEditing(null)} onSave={save} upload={actions.upload}/>}</section>;
}