import React, { useEffect, useRef } from 'react';
const pointXY=p=>Array.isArray(p)?p:[p.x,p.y];
export default function ObjectPreviewCanvas({objects,selectedId,hideOthers,imageUrl,dstAnalysis}) {
  const canvasRef=useRef(null), imageRef=useRef(null), cache=useRef(new Map());
  useEffect(()=>{ if(!imageUrl){imageRef.current=null;return;} const img=new Image(); img.onload=()=>{imageRef.current=img;draw();}; img.src=imageUrl; },[imageUrl]);
  const draw=()=>{ const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext('2d'),w=canvas.clientWidth,h=canvas.clientHeight,dpr=devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;ctx.scale(dpr,dpr);ctx.fillStyle='#0b0d12';ctx.fillRect(0,0,w,h);if(imageRef.current)ctx.drawImage(imageRef.current,0,0,w,h);
    const shown=hideOthers?objects.filter(o=>o.id===selectedId):objects, allBounds=objects.reduce((b,o)=>({minX:Math.min(b.minX,o.bounds.minX),minY:Math.min(b.minY,o.bounds.minY),maxX:Math.max(b.maxX,o.bounds.maxX),maxY:Math.max(b.maxY,o.bounds.maxY)}),{minX:Infinity,minY:Infinity,maxX:-Infinity,maxY:-Infinity}),sx=(w-40)/Math.max(1,allBounds.maxX-allBounds.minX),sy=(h-40)/Math.max(1,allBounds.maxY-allBounds.minY),s=Math.min(sx,sy),tx=x=>20+(x-allBounds.minX)*s,ty=y=>20+(y-allBounds.minY)*s;
    shown.forEach(o=>{ const key=`${o.id}:${o.points.length}`, path=cache.current.get(key)||new Path2D(); if(!cache.current.has(key)){if(o.points.length){o.points.forEach((p,i)=>{const [x,y]=pointXY(p);i?path.lineTo(tx(x),ty(y)):path.moveTo(tx(x),ty(y));});path.closePath();}else path.rect(tx(o.bounds.minX),ty(o.bounds.minY),Math.max(2,o.width*s),Math.max(2,o.height*s));cache.current.set(key,path);}ctx.globalAlpha=o.id===selectedId?0.85:0.42;ctx.fillStyle=o.relations.hole||o.relations.exclusion?'#0b0d12':o.color;ctx.fill(path);ctx.globalAlpha=1;ctx.strokeStyle=o.id===selectedId?'#f8fafc':'#64748b';ctx.lineWidth=o.id===selectedId?3:1;ctx.stroke(path);ctx.save();ctx.clip(path);ctx.strokeStyle='rgba(255,255,255,.55)';ctx.lineWidth=1;const spacing=Math.max(4,(o.parameters.spacing||.4)*12);for(let y=-h;y<h*2;y+=spacing){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y+Math.tan((o.parameters.angle||0)*Math.PI/180)*w);ctx.stroke();}ctx.restore();ctx.fillStyle='#fff';ctx.font='10px sans-serif';ctx.fillText(`#${o.order+1} ${o.technique}`,tx(o.bounds.minX)+3,ty(o.bounds.minY)+12);});
    const g=dstAnalysis?.geometry;if(g){ctx.setLineDash([4,4]);ctx.strokeStyle='#f59e0b';ctx.globalAlpha=.5;ctx.beginPath();for(let i=0;i<g.count;i++){const x=tx(g.xs[i]),y=ty(g.ys[i]);i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;}
  };
  useEffect(draw,[objects,selectedId,hideOthers,dstAnalysis]);
  return <canvas ref={canvasRef} aria-label="Previsualización de objetos, técnicas, orden, contornos y jumps" className="h-[560px] w-full rounded-lg border border-border bg-background"/>;
}